version: '3.8'
services:
  frontend:
    image: rongem/boat3-extensions:latest
    ports:
      - 80:80
    build:
      dockerfile: Dockerfile.frontend
      context: .
#    restart: always
  backend:
    image: rongem/boat3-extensions:backend
    build:
      dockerfile: Dockerfile.backend
      context: .
    environment:
      - DB_NAME
      - DB_SERVER
      - DB_USER
      - DB_PWD
      - CORS_ORIGIN
      - AUTH_MODE
      - LDAP_DOMAIN
      - LDAP_SERVER
    extra_hosts:
      - "micron:192.168.178.20"

    
