FROM node:lts AS build
WORKDIR /usr/app

COPY ./frontend/package*.json ./
RUN npm update --location=global # only if image was too old
RUN npm install --force --verbose
COPY ./frontend/ ./
RUN npm run build:prod

FROM nginx
WORKDIR /usr/app
COPY --from=build /usr/app/dist/frontend /usr/share/nginx/html/
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
