# specify a base image for compiling
FROM node:lts AS build
WORKDIR /usr/app

# install dependencies
COPY ./backend/package*.json ./
RUN npm install
COPY ./backend/ ./
RUN npm run comp

# specify base image
FROM node:lts-alpine
WORKDIR /usr/app

# install dependencies
COPY ./backend/package*.json ./
COPY --from=build /usr/app/dist ./dist
RUN npm update -g
RUN npm ci --only-production

# port
EXPOSE 8000
# default command
CMD ["npm", "start"]
