version: '3.8'
services:
  frontend:
    image: rongem/boat3-extensions:frontend
    ports:
      - 80:80
    build:
      dockerfile: Dockerfile.frontend
      context: .
#    restart: always
  backend:
    image: rongem/boat3-extensions:backend
    build:
      dockerfile: Dockerfile.backend
      context: .
    environment:
      - DB_NAME
      - DB_SERVER
      - DB_USER
      - DB_PWD
      - LDAP_DOMAIN
      - LDAP_SERVER
  apache-ds:
    image: tgbyte/apacheds
  database:
    image: fosibyte/sqlexpress-2019


    
